### ISSUE TITLE
In or out of the mesh

### ISSUE THREAD

**Issue by nicoodle** [AOEpeople/kubernetes-sidecar-cleaner#1]
Fantastic work on this.
I've one small question, should the controller be deployed so that it's within the mesh or outside of the mesh? 
We've current got it deployed outside the mesh and though it's working as expected we are getting the following log outputs:

```
I0810 14:30:26.138086       1 controller.go:84] removing CRONJOB 0 1
I0810 14:30:26.138112       1 cleaner.go:33] removing CRONJOB
I0810 14:30:26.153409       1 controller.go:98] Error syncing pod default/CRONJOB: unable to upgrade connection: container not found ("istio-proxy") failed executing on default/CRONJOB
```

Thanks!

**Comment by tolleiv** [comment]
Sorry for the late response, the controller does not need to be part of the mesh as it only communicates through the Kubernetes API.
